version: "3"

services:

    miwebapp:
        container_name: miwebapp
        image: miwebapp:desarrollo
        build: 
            context: .
            args:
                REPO_APP: https://github.com/IvanciniGT/cursoJenkinsWebapp
        environment:
                PUERTO_TOMCAT: 8084
        #    - TOMCAT_PASSWORD=password
        ports:
            - 8082:8084