version: "3"   # La versión del esquema YAML de docker-compose que estoy utilizando

services:
    
    mariadb:            # Este nombre es un fqdn que puedo usar en la red de docker
        container_name: mimariadb 
        image:          mariadb:latest
        environment:
                        - MARIADB_USER=usuario
                        - MARIADB_PASSWORD=password
                        - MARIADB_ROOT_PASSWORD=password
                        - MARIADB_DATABASE=curso
        #ports:
        #                - 0.0.0.0:3307:3306
        volumes:
                        - /home/ubuntu/environment/datos/mariadb:/var/lib/mysql
    
    wordpress:
        container_name: miwordpress
        image:          wordpress #:latest
        environment:
                        WORDPRESS_DB_HOST: mariadb:3306
                        WORDPRESS_DB_USER: usuario
                        WORDPRESS_DB_PASSWORD: password
                        WORDPRESS_DB_NAME: curso
        ports: 
                        - 8080:80
        volumes:        
                        - /home/ubuntu/environment/datos/wordpress:/var/www/html
